# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BodyDetection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CorePlot', '~> 2.3'
  # Pods for BodyDetection

end
